workers = [
    {
        "country_name": "Australia",
        "country_code": "AU",
        "continent": "Europe",
        "city": "Sydney",
        "ip": "139.99.140.84",
    },
    {
        "country_name": "Brazil",
        "country_code": "BR",
        "continent": "SouthAmerica",
        "city": "Sao_Paulo",
        "ip": "45.179.89.35",
    },
    {
	"country_name": "Germany",
	"country_code": "DE",
        "continent": "Europe",
	"city": "Kassel",
	"ip": "136.243.129.182",
	
    },
    {
        "country_name": "India",
        "country_code": "IN",
        "continent": "Asia",
        "city": "Noida",
        "ip": "103.129.97.180",
    },
    {
        "country_name": "Italy",
        "country_code": "IT",
        "continent": "Europe",
        "city": "Milan",
        "ip": "94.198.97.45",
    },
    {
        "country_name": "Japan",
        "country_code": "JP",
        "continent": "Asia",
        "city": "Tokyo",
        "ip": "210.140.10.50",
    },
    {
        "country_name": "Russia",
        "country_code": "RU",
        "continent": "Asia",
        "city": "Moscow",
        "ip": "158.255.2.65",
    },
    {
        "country_name": "Singapore",
        "country_code": "SG",
        "continent": "Asia",
        "city": "NA",
        "ip": "139.99.31.107",
    },
    {
        "country_name": "South Africa",
        "country_code": "SA",
        "continent": "Africa",
        "city": "Johannesburg",
        "ip": "102.130.116.16"
    },
    {
        "country_name": "South Korea",
        "country_code": "SK",
        "continent": "Asia",
        "city": "Seoul",
        "ip": "27.255.75.155",
    },
    {
        "country_name": "Turkey",
        "country_code": "TR",
        "continent": "Asia",
        "city": "Istanbul",
        "ip": "152.89.36.213",
    },
    {
        "country_name": "United Kingdom",
        "country_code": "UK",
        "continent": "Africa",
        "city": "London",
        "ip": "79.141.170.113",
    },
    {
        "country_name": "Ukraine",
        "country_code": "UKR",
        "continent": "Asia",
        "city": "Kyiv",
        "ip": "176.107.188.184",
    },
    {
        "country_name": "China",
        "country_code": "CH",
        "continent": "Asia",
        "city": "Guangzhou",
        "ip": "106.55.49.211",
    },
    {
        "country_name": "China",
        "country_code": "CH",
        "continent": "Asia",
        "city": "Chengdu",
        "ip": "118.24.106.35",
    },
    {   "country_name": "China",
        "country_code": "CH",
        "continent": "Asia",
        "city": "Nanjing",
        "ip": "119.45.229.79",
    },
    {
        "country_name": "Hongkong",
        "country_code": "HK",
        "continent": "Asia",
        "city": "NA",
        "ip": "129.226.185.138",
    },
    {
        "country_name": "China",
        "country_code": "CH",
        "continent": "Asia",
        "city": "Chongqing",
        "ip": "129.28.200.94",
    },
    {
        "country_name": "China",
        "country_code": "CH",
        "continent": "Asia",
        "city": "Beijing",
        "ip": "152.136.208.91",
    },
    {
        "country_name": "China",
        "country_code": "CH",
        "continent": "Asia",
        "city": "Shanghai",
        "ip": "81.68.130.31",
    },
    {
        "country_name": "Egypt",
        "country_code": "EG",
        "continent": "Europe",
        "city": "NA",
        "ip": "196.46.191.125",
    },
    {
        "country_name": "Bulgaria",
        "country_code": "BG",
        "continent": "Europe",
        "city": "NA",
        "ip": "193.37.215.80",
    },
    {
        "country_name": "United States",
        "country_code": "US",
        "continent": "United States",
        "city": "Dallas",
        "ip": "45.176.188.31",
    },
    {
        "country_name": "Egypt",
        "country_code": "EG",
        "continent": "Europe",
        "city": "cairo",
        "ip": "196.46.191.118",
    },
    {
        "country_name": "France",
        "country_code": "FR",
        "continent": "Europe",
        "city": "France",
        "ip": "194.99.23.123",
    },
    {
        "country_name": "Germany",
        "country_code": "DE",
        "continent": "Europe",
        "city": "NA",
        "ip": "93.115.19.234",
    },	
    {
        "country_name": "Greece",
        "country_code": "GR",
        "continent": "Europe",
        "city": "Greece",
        "ip": "185.234.52.94",
    },
    {
        "country_name": "Japan",
        "country_code": "JP",
        "continent": "Asia",
        "city": "Japan",
        "ip": "85.208.110.239",
    },
    {
        "country_name": "Mexico",
        "country_code": "MX",
        "continent": "North America",
        "city": "Mexico",
        "ip": "131.196.253.138",
    },
    {
        "country_name": "United States",
        "country_code": "US",
        "continent": "United States",
        "city": "Miami",
        "ip": "45.164.20.145",
    },
    {
        "country_name": "Singapore",
        "country_code": "SG",
        "continent": "Asia",
        "city": "NA",
        "ip": "210.16.120.249",
    },
    {
        "country_name": "Sweden",
        "country_code": "SE",
        "continent": "Europe",
        "city": "Sweden",
        "ip": "185.243.215.157",
    },
    {
        "country_name": "Turkey",
        "country_code": "TR",
        "continent": "Asia",
        "city": "Bursa",
        "ip": "185.65.206.202",
    },
    {
        "country_name": "United_Kingdom",
        "country_code": "UK",
        "continent": "Europe",
        "city": "London",
        "ip": "178.157.82.66",
    },

    {
        "country_name": "South Korea",
        "country_code": "SK",
        "continent": "Asia",
        "city": "Seoul",
        "ip": "103.140.45.111",
    },
    {
        "country_name": "United States",
        "country_code": "US",
        "continent": "America",
        "city": "LosAngeles",
        "ip": "45.170.251.248",
    },
    {
        "country_name": "Argentina",
        "country_code": "AR",
        "continent": "SouthAmerica",
        "city": "Cordoba",
        "ip": "190.103.177.37",
    },
    {
        "country_name": "Australia_brisbane",
        "country_code": "AUS",
        "continent": "Asia",
        "city": "NA",
        "ip": "45.248.77.52",
    },
    {
        "country_name": "Brazil2",
        "country_code": "BR",
        "continent": "SouthAmerica",
        "city": "NA",
        "ip": "45.231.133.131",
    },
    {
        "country_name": "Canada1",
        "country_code": "CA",
        "continent": "NorthAmerica",
        "city": "Toronto",
        "ip": "66.85.30.94",
    },
    {
        "country_name": "Canada2",
        "country_code": "CA",
        "continent": "NorthAmerica",
        "city": "Toronto",
        "ip": "66.85.30.96",
    },
    {
        "country_name": "Colombia",
        "country_code": "CO",
        "continent": "SouthAmerica",
        "city": "NA",
        "ip": "190.120.231.14",
    },
    {
        "country_name": "Germany3",
        "country_code": "DE",
        "continent": "Europe",
        "city": "NA",
        "ip": "158.255.215.175",
    },
    {
        "country_name": "Egypt3",
        "country_code": "EG",
        "continent": "Europe",
        "city": "NA",
        "ip": "41.215.240.135",
    },
    {
        "country_name": "France2",
        "country_code": "FR",
        "continent": "Europe",
        "city": "NA",
        "ip": "158.255.215.175",
    },
    {
        "country_name": "Mumbai_IN",
        "country_code": "IN",
        "continent": "Asia",
        "city": "Mumbai",
        "ip": "103.86.177.2",
    },
    {
        "country_name": "Bangalore_IN",
        "country_code": "IN",
        "continent": "Asia",
        "city": "Bangalore",
        "ip": "159.65.158.78",
    },
    {
        "country_name": "Iran",
        "country_code": "IR",
        "continent": "Asia",
        "city": "NA",
        "ip": "185.187.49.249",
    },
    {
        "country_name": "Italy2",
        "country_code": "IT",
        "continent": "Europe",
        "city": "Milan",
        "ip": "149.154.157.199",
    },
    {
        "country_name": "Japan2",
        "country_code": "JP",
        "continent": "Asia",
        "city": "NA",
        "ip": "180.149.230.23",
    },
    {
        "country_name": "South_Korea2",
        "country_code": "KR",
        "continent": "Asia",
        "city": "NA",
        "ip": "202.168.154.57",
    },
    {
        "country_name": "Mexico2",
        "country_code": "MX",
        "continent": "NorthAmerica",
        "city": "NA",
        "ip": "190.103.179.7",
    },
    {
        "country_name": "Peru",
        "country_code": "PE",
        "continent": "SouthAmerica",
        "city": "NA",
        "ip": "190.120.229.6",
    },
    {
        "country_name": "Russia",
        "country_code": "RU",
        "continent": "Asia",
        "city": "Moscow",
        "ip": "213.183.56.83",
    },
    {
        "country_name": "Siberia",
        "country_code": "RU",
        "continent": "Asia",
        "city": "Khabarovsk",
        "ip": "92.223.72.165",
    },
    {
        "country_name": "Siberia",
        "country_code": "RU",
        "continent": "Asia",
        "city": "Novosibirsk",
        "ip": "217.65.87.244",
    },
    {
        "country_name": "Singapore2",
        "country_code": "SG",
        "continent": "Asia",
        "city": "NA",
        "ip": "103.216.223.23",
    },
    {
        "country_name": "Turkey2",
        "country_code": "TR",
        "continent": "Europe",
        "city": "NA",
        "ip": "46.20.1.88",
    },
    {
        "country_name": "Ukraine",
        "country_code": "UA",
        "continent": "Europe",
        "city": "NA",
        "ip": "91.203.145.201",
    },
    {
        "country_name": "UK2",
        "country_code": "UK",
        "continent": "Europe",
        "city": "NA",
        "ip": "46.17.63.208",
    },
    {
        "country_name": "South_Africa",
        "country_code": "ZA",
        "continent": "Africa",
        "city": "NA",
        "ip": "169.255.58.210",
    },
]

"""
All VPS need some fixes
"""


