- hosts: all
  gather_facts: false
  vars_files:
    - .env

  tasks:


    # User configuration
    - name: Change root password
      user: name=root password="{{ ROOT_PASSWORD }}"

    - name: Create .ssh directory
      file:
        path: /root/.ssh
        state: directory
        mode: 0700

    - name: Add authorized keys
      copy:
        src: authorized_keys
        dest: /root/.ssh/authorized_keys
        mode: "0644"


    # apt
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: "yes"
